gbm/gbm-symbols-check: rework to a bidirectional test
Original test attributed only when the library exports new symbols.
It did not consider when symbol disappears... case of which has happened
in the past.

Update the test, removing the artificial restriction for only T symbols.
This brings wl_drm_interface to the list... which should be addressed by
wayland-scanner.

Signed-off-by: Emil Velikov <emil.velikov@collabora.com>

diff --git a/src/gbm/gbm-symbols-check b/src/gbm/gbm-symbols-check
--- a/src/gbm/gbm-symbols-check
+++ b/src/gbm/gbm-symbols-check
@@ -1,8 +1,18 @@
 #!/bin/sh
 
-FUNCS=$(nm -D --defined-only ${1-.libs/libgbm.so} | grep -o "T .*" | cut -c 3- | while read func; do
-( grep -q "^$func$" || echo $func )  <<EOF
-gbm_device_get_fd
+AVAIL_FUNCS="$(nm -D --format=bsd --defined-only ${1-.libs/libgbm.so} | awk '{print $3}')"
+
+# Platform specific, "optional", symbols.
+PLAT_FUNCS="__bss_start
+_edata
+_end
+_fini
+_init
+"
+
+# Official ABI, taken from the public headers.
+# Note: wl_drm_interface should not be here, but that requires wayland-scanner fixes.
+REQ_FUNCS="gbm_device_get_fd
 gbm_device_get_backend_name
 gbm_device_is_format_supported
 gbm_device_destroy
@@ -37,10 +47,25 @@ gbm_surface_lock_front_buffer
 gbm_surface_release_buffer
 gbm_surface_has_free_buffers
 gbm_surface_destroy
-_fini
-_init
-EOF
+wl_drm_interface
+"
+
+NEW_ABI=$(echo "$AVAIL_FUNCS" | while read func
+do
+    echo "$REQ_FUNCS" | grep -q "^$func$" && continue
+    echo "$PLAT_FUNCS" | grep -q "^$func$" && continue
+
+    echo $func
 done)
 
-test ! -n "$FUNCS" || echo $FUNCS
-test ! -n "$FUNCS"
+test ! -n "$NEW_ABI" || echo "New ABI detected - If intentional, update the test."; echo "$NEW_ABI"
+
+REMOVED_ABI=$(echo "$REQ_FUNCS" | while read func
+do
+    echo "$AVAIL_FUNCS" | grep -q "^$func$" && continue
+
+    echo $func
+done)
+
+test ! -n "$REMOVED_ABI" || echo "ABI break detected - Required symbol(s) no longer exported!"; echo "$REMOVED_ABI"
+test ! -n "$NEW_ABI" || test ! -n "$REMOVED_ABI"
