egl/egl-symbols-check: rework to a bidirectional test
Like earlier commit - rework the test to attribute both:
 - new ABI
 - or removed one

Ideally either of these will happen. Sadly it had in the past.

Signed-off-by: Emil Velikov <emil.velikov@collabora.com>

diff --git a/src/egl/egl-symbols-check b/src/egl/egl-symbols-check
--- a/src/egl/egl-symbols-check
+++ b/src/egl/egl-symbols-check
@@ -1,8 +1,20 @@
 #!/bin/sh
 
-FUNCS=$(nm -D --defined-only ${1-.libs/libEGL.so} | grep -o "T .*" | cut -c 3- | while read func; do
-( grep -q "^$func$" || echo $func )  <<EOF
-eglBindAPI
+AVAIL_FUNCS="$(nm -D --format=bsd --defined-only ${1-.libs/libEGL.so} | awk '{print $3}')"
+
+# Platform specific, "optional", symbols.
+PLAT_FUNCS="__bss_start
+_edata
+_end
+_fini
+_init
+"
+
+# Official ABI, taken from the public headers.
+# Note: wl_drm_interface should not be here, but that requires wayland-scanner fixes.
+# Note: MesaGLInteropEGL* are internal symbols used for interoperability across
+# different APIs. See mesa_glinterop.h for details.
+REQ_FUNCS="eglBindAPI
 eglBindTexImage
 eglChooseConfig
 eglCopyBuffers
@@ -38,10 +50,25 @@ eglWaitGL
 eglWaitNative
 MesaGLInteropEGLQueryDeviceInfo
 MesaGLInteropEGLExportObject
-_fini
-_init
-EOF
+wl_drm_interface
+"
+
+NEW_ABI=$(echo "$AVAIL_FUNCS" | while read func
+do
+    echo "$REQ_FUNCS" | grep -q "^$func$" && continue
+    echo "$PLAT_FUNCS" | grep -q "^$func$" && continue
+
+    echo $func
 done)
 
-test ! -n "$FUNCS" || echo $FUNCS
-test ! -n "$FUNCS"
+test ! -n "$NEW_ABI" || echo "New ABI detected - If intentional, update the test."; echo "$NEW_ABI"
+
+REMOVED_ABI=$(echo "$REQ_FUNCS" | while read func
+do
+    echo "$AVAIL_FUNCS" | grep -q "^$func$" && continue
+
+    echo $func
+done)
+
+test ! -n "$REMOVED_ABI" || echo "ABI break detected - Required symbol(s) no longer exported!"; echo "$REMOVED_ABI"
+test ! -n "$NEW_ABI" || test ! -n "$REMOVED_ABI"
